### ISSUE TITLE
Support nullable values (nullable:true)

### ISSUE THREAD

**Issue by lezhnev74** [hkarlstrom/openapi-validation-middleware#11]
I just stumbled upon this problem. Looks like nullable validation is not performed correctly.

Specification contains this schema:
```json
"before_sale_price": {
  "type": "integer",
  "minimum": 0,
  "nullable": true,
  "description": "A price before discounts applied"
}
```

When I run the validation process, I get this error:
```json
{
        "name": "data.data.0.before_sale_price",
        "code": "error_type",
        "value": null,
        "in": "body",
        "expected": "integer",
        "used": "null"
}
```

I think this is related to #8 because canonic JSON Schema supports this format:
```json
"before_sale_price": {
  "type": ["integer",null]
},
```

Do you think I should convert the schema to JSON Schema first here?

**Comment by hkarlstrom** [comment]
I couldn't reproduce that? Could you provide the openapi specification you used so I can use that while testing?

**Comment by lezhnev74** [comment]
Sure, I'll add a failing test first.
