### ISSUE TITLE
Validate query parameters that are objects

### ISSUE THREAD

**Issue by hkarlstrom** [hkarlstrom/openapi-validation-middleware#18]
More info: [https://swagger.io/docs/specification/describing-parameters/#query-parameters](https://swagger.io/docs/specification/describing-parameters/#query-parameters)

Currently these are not validated at all.

**Comment by shadowhand** [comment]
https://swagger.io/docs/specification/serialization/#query possibly also useful.

**Comment by hkarlstrom** [comment]
Fixed in b63ce9309edd7170e8c4badafafb1cafcec37be2
