### ISSUE TITLE
Make `validateRequest` public

### ISSUE THREAD

**Issue by lezhnev74** [hkarlstrom/openapi-validation-middleware#2]
Hey!
I wonder if you think the method could be public (just like the other ones: `validateResponseHeaders`,`validateResponseBody` ), so the library can be used not as a middleware but rather as a validation library like this:
```
$validator = new OpenApiValidation(...);
$validator->validateRequest($request);
```

It feels that middleware is just a single application for the underlying validator. 
There could be more. For example, validating of logged requests & responses.

**Comment by francescozanoni** [comment]
A quick-n-dirty workaround:

```
$reflector = new ReflectionObject($validator);
$method = $reflector->getMethod('validateRequest');
$method->setAccessible(true);
$errors = $method->invokeArgs($validator, [&$psr7Request, $path, $httpMethod, $pathParameters]);
```

Thanks to https://stackoverflow.com/questions/2738663/call-private-methods-and-private-properties-from-outside-a-class-in-php

**Comment by lezhnev74** [comment]
Well, that is ok for tests, but I'd better not do things like that in our project :)
Actually, I ended up with this code:
```php
# This is a noop handler to conform to
$handler = new class implements RequestHandlerInterface
{
        public function handle(ServerRequestInterface $request): ResponseInterface
        {
            return new Response();
        }
};
$validator->process($request, $handler);
```

**Comment by hkarlstrom** [comment]
I think it makes sense to separate the middleware and the validator as you suggested! I’ll look in to it.
